apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-website
  labels:
    app: school-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: school-website
  template:
    metadata:
      labels:
        app: school-website
    spec:
      containers:
      - name: school-website
        image: yogismash/school-img:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: school-website-service
spec:
  selector:
    app: school-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
